### ISSUE TITLE
 "cancel" button should also remove the speaker name

### ISSUE THREAD

**Issue by annyhe** [toastmasters-dev/quip-toastmasters#13]

**Comment by mxxk** [comment]
@annyhe, I just did a quick proof-of-concept of this and it seems like it's best we keep the functionality as-is. 🙂 The "Cancel" button is there specifically for the speaker to clear the currently selected speech project, perhaps due to an error or to start over. If their name gets cleared at the same time, it feels jarring. This gets even more shocking if the behavior is made more consistent by also clearing the speech title as well...

Suppose you're an innocent speaker who entered her name, followed by "My Awesome Speech Title", and in your overwhelming joy selected "Ice Breaker". But you're actually _Advanced Communicator Over Nine Thousand_, and you meant to select "Super Difficult Speech #99", so you hit "Cancel". Boom! 💥 Not only is the project cleared, but so is your name and speech title. Now you're scratching your head... "What was that speech title again?" 🤔💭 

If the current UI is not as clear about what the "Cancel" button really does, I'm more than happy to consider other text to make it more obvious. Or perhaps an ❌ emoji?

Closing this issue, but feel free to reopen if you feel otherwise. 😄

**Comment by annyhe** [comment]
Ok sounds good Max.

On March 5, 2019 at 8:24 PM, Max Kukartsev <notifications@github.com> wrote:

@annyhe <https://github.com/annyhe>, I just did a quick proof-of-concept of
this and it seems like it's best we keep the functionality as-is. 🙂 The
"Cancel" button is there specifically for the speaker to clear the
currently selected speech project, perhaps due to an error or to start
over. If their name gets cleared at the same time, it feels jarring. This
gets even more shocking if the behavior is made more consistent by also
clearing the speech title as well...

Suppose you're an innocent speaker who entered her name, followed by "My
Awesome Speech Title", and in your overwhelming joy selected "Ice Breaker".
But you're actually *Advanced Communicator Over Nine Thousand*, and you
meant to select "Super Difficult Speech #99", so you hit "Cancel". Boom! 💥
Not only is the project cleared, but so is your name and speech title. Now
you're scratching your head... "What was that speech title again?" 🤔💭

If the current UI is not as clear about what the "Cancel" button really
does, I'm more than happy to consider other text to make it more obvious.
Or perhaps an ❌ emoji?

Closing this issue, but feel free to reopen if you feel otherwise. 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/toastmasters-dev/quip-toastmasters/issues/13#issuecomment-469963133>,
or mute the thread
