### ISSUE TITLE
Speech length beyond 56 minutes

### ISSUE THREAD

**Issue by borncrusader** [toastmasters-dev/quip-toastmasters#4]
If we choose 2 speeches that are around 15 minutes, the agenda barfs saying we cannot fit the meeting within 55 minutes.

**Comment by mxxk** [comment]
Yes, at the moment it is behaving as desired. If both speeches are 15 minutes, there isn't even enough time for evaluations... In this case, what would you like the agenda app to do?

(Also, since this issue refers to [toastmasters-dev/print-agenda](https://github.com/toastmasters-dev/print-agenda), moving it there...)

**Comment by mxxk** [comment]
This issue was moved to toastmasters-dev/print-agenda#2

**Comment by mxxk** [comment]
(By the way, the issue was moved using https://github-issue-mover.appspot.com/, based on https://github.com/google/github-issue-mover)
